import Header from "@/components/custom/header";
import { Toaster } from "@/components/ui/toaster";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"], variable: "--font-sans" });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "min-h-screen bg-slate-100 font-sans antialiased flex flex-col justify-start items-center pb-10",
          inter.variable,
        )}
      >
        <Header />
        <main className="px-6">{children}</main>
        <Toaster />
      </body>
    </html>
  );
}
